hint = "THE ARCANUM. THREE HALLS, THREE RODS OF POWER. EACH SEAL BREAKS WHEN ITS GUARDIAN IN THE TOWERS FALLS... AND ONLY IN ORDER: FLAME, THEN FROST, THEN STORM.";
hint2 = "THE LEFT STAIRS: FLAME, AFTER THE SOUTHERN TOWER. THE MIDDLE: FROST, AFTER THE BOG TOWER AND WITH THE FIRE ROD. THE RIGHT: STORM, AFTER LADHELLIN AND WITH THE ICE ROD.";
