hint = "THE HALL OF FROST. TWO LOCKS AGAIN. WEST, FLAMES OUT OF REACH. EAST, STONES AND SWITCHES.";
hint2 = "WEST: THE FIRE ROD FLIES OVER PITS. EAST: THREE SWITCHES BUT TWO BLOCKS: THE THIRD IS YOU.";
