hint = "THREE SWITCHES, TWO STONES. A SWITCH ONLY HOLDS WHILE SOMETHING SITS ON IT... BUT YOU COUNT AS SOMETHING.";
hint2 = "THE LONE SWITCH IN THE SOUTH-EAST IS FOR YOU. BOTH STONES GO ON THE PAIR ABOVE IT. THE STONES MUST TAKE TURNS: NEITHER GETS THERE ALONE.";
