hint = "THE HALL OF STORMS. THE VAULT NORTH HOLDS THE LAST GIFT OF THE ARCANUM. ITS BIG KEY LIES EAST, BEYOND REACH UNTIL YOU HOLD THE STORM ITSELF.";
hint2 = "GO WEST FOR THE SMALL KEY FIRST. THE LIGHTNING ROD IS NORTH, PAST THE POOL. THEN GO EAST.";
