hint = "TWO SWITCHES: ONE ASHORE, ONE ON THE ISLAND. ONE STONE BLOCK. STONE SINKS IN WATER... BUT NOT ON ICE.";
hint2 = "FREEZE A LINE OF FLOES FROM THE BLOCK TO THE ISLAND AND PUSH IT ACROSS QUICKLY. THEN STAND ON THE SWITCH ASHORE.";
