hint = "THE HALL OF FLAME. ITS HEART LIES NORTH, BEHIND TWO LOCKS. ONE KEY WAITS WEST, ONE EAST.";
hint2 = "WEST: PUSH THE STONE BLOCKS ONTO THE SWITCHES. EAST: THE CRYSTAL IS OUT OF REACH OF YOUR SWORD... BUT NOT OF A THROW.";
