hint = "THE VAULT DOOR WANTS THE BIG KEY. IT LIES EAST OF THE STAIRS, PAST FIRE, ICE AND A FAR CRYSTAL.";
hint2 = "GO BACK TO THE ROOM WITH THE STAIRS AND TAKE THE EAST DOOR. YOU'LL NEED ALL THREE RODS.";
