hint = "THE WATER RUSHES TOWARDS YOU: NO ONE COULD SWIM IT. THE FLAMES WON'T LET YOU NEAR.";
hint2 = "FREEZE THE FLAME JET. THEN FREEZE THE WATER ONE TILE AT A TIME AND WALK ACROSS BEFORE IT MELTS.";
